Numpy examples

In [5]:
import numpy as np

In [6]:
my_list = [1,2,3]

In [7]:
arr = np.array(my_list)

In [8]:
arr

array([1, 2, 3])

In [9]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]]

In [10]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones(4)

array([1., 1., 1., 1.])

In [15]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.random.rand(2,5)

array([[0.54891061, 0.98881614, 0.84943832, 0.49856018, 0.59579543],
       [0.71361468, 0.77844024, 0.93220975, 0.70894134, 0.32062091]])

In [19]:
np.random.randn(4,4)

array([[ 0.02730817, -0.02122042,  1.19022528, -0.57468244],
       [-0.43796983, -1.23903513,  0.73450589,  0.38794957],
       [ 0.51751137, -0.68365023, -1.21623554,  0.00818625],
       [ 0.71069057,  1.72018447, -0.64983293,  0.52245175]])

In [20]:
np.random.randint(1,100,10)

array([81, 38, 16, 48,  1, 18, 43, 86, 52, 55])

In [21]:
ranarr = np.random.randint(0,50,10)

In [22]:
ranarr

array([47,  8, 20, 22,  7, 27, 21,  0, 44,  6])

In [28]:
ranarr.max()

47

In [29]:
ranarr.min()

0

In [30]:
ranarr

array([47,  8, 20, 22,  7, 27, 21,  0, 44,  6])

In [31]:
ranarr.argmax()

0

In [32]:
ranarr.argmin()

7

In [37]:
from numpy.random import randint

In [38]:
randint(2,10)

4

In [39]:
arr = np.arange(0,11)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
arr[8]

8

In [42]:
arr[1:5]

array([1, 2, 3, 4])

In [43]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [44]:
arr[6:]

array([ 6,  7,  8,  9, 10])

In [45]:
arr[0:5] = 100

In [46]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [47]:
arr = np.arange(0,11)

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
slice_of_arr = arr[0:6]

In [50]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [51]:
slice_of_arr[:] = 99

In [52]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [53]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [54]:
arr_copy = arr.copy()

In [55]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [56]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [57]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [58]:
arr_2d[1][2]

30

In [59]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [60]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [61]:
arr = np.arange(1,11)

In [62]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [65]:
bool_arr = arr > 5

In [66]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [67]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [68]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [69]:
arr[arr<3]

array([1, 2])

In [70]:
arr_2d = np.arange(50).reshape(5,10)

In [73]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [74]:
arr = np.arange(0,11)

In [75]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [77]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [78]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [79]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [80]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [81]:
np.max(arr)

10

In [82]:
arr.max()

10

In [83]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [84]:
np.log(arr)

/home/cami/myvenv/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])